### ISSUE TITLE
Move Generic Connection Panel

### ISSUE THREAD

**Issue by LucianoZu** [Ardulink/Ardulink-2#12]
Generic Connection Panel should be a generic component in ardulink-swing.
Examples already use it.

@pfichtner if you agree I'll do it asap.

**Comment by pfichtner** [comment]
Do you mean ConnectionPanel and GenericPanelBuilder? Or just ConnectionPanel? Anyway: If one or both of them can be reused by other components feel free to move them to ardulink-swing.

**Comment by LucianoZu** [comment]
Ok, I mean all the classes used for build the connection screen on console. Well I'll do it asap

**Comment by LucianoZu** [comment]
I had to copy some classes for test unit (for example DummyLinkFactory or BaseBuilder). Peter if this is not the best practice, please leave to me a comment or move this issue to done status.

**Comment by pfichtner** [comment]
Classes in test are things that test classes/units in the same maven module. If the system under test (SUT) gets moved those tests have to been moved, too. There is absolutely no need to duplicate things. I deleted the corresponding classes.
