### ISSUE TITLE
CI build on Ardulink-2

### ISSUE THREAD

**Issue by pfichtner** [Ardulink/Ardulink-2#2]
We should do a CI build on Ardulink-2. Travis-CI could be a choice. Since I am missing the admin access attribute on Ardulink-2 I cannot do this by myself.

**Comment by LucianoZu** [comment]
Travis CI is configured to run a build (clean package). Please check it and check if your account is contacted by Travis. Then close this issue.

Now you have also admin privileges on Ardulink 2

**Comment by pfichtner** [comment]
Works like a charm
