### ISSUE TITLE
MQTT Authorization support

### ISSUE THREAD

**Issue by keyndark** [Ardulink/Ardulink-2#27]
Hi. I'm not found in docs how to pass authorization credentials for MQTT server. Is this feature supported or any plan to implement it?

**Comment by pfichtner** [comment]
Adding authorization is not a great thing and could be added without any problem. In which component are you missing it? MqttMain? ArdulinkConsole?

**Comment by pfichtner** [comment]
MqttMain in git repo now supporting authentification

**Comment by pfichtner** [comment]
MqttLink in git repo now supporting authentification

**Comment by keyndark** [comment]
Great! Thank you!

**Comment by pfichtner** [comment]
Since for now there's now way for downloading the artifacts of Ardulink's CI build you'll have to pull and build by yourself or to wait for the next Ardulink release

**Comment by pfichtner** [comment]
@LucianoZu Please close when releasing

**Comment by pfichtner** [comment]
Enhancement included in release v2.1.0 Gordio
