### ISSUE TITLE
Error on Ardulink Console

### ISSUE THREAD

**Issue by JuniorEC** [Ardulink/Ardulink-2#33]
![image](https://user-images.githubusercontent.com/24255719/32193635-b3caf1f2-bd96-11e7-8ccf-081e8895daae.png)

During the execution of the Ardulink Console, the attached error appeared. Is something missing to run?

**Comment by LucianoZu** [comment]
Please read the stack trace log on Java console.

**Comment by pfichtner** [comment]
However the OP did accomplished that but that's the message you get when deleting ardulink-core-beans.jar from the lib folder. I guess the stacktrace tells ```java.lang.NoClassDefFoundError: org/ardulink/core/beans/BeanProperties```

**Comment by pfichtner** [comment]
To make life easier in future I added the exception's class name to the JPanel and the error dialog with commit 8d3a96b7ffb12cc502eb09795f41350efd4049dc
