### ISSUE TITLE
Button to publish to MQTT, LED to receive MQTT subscriptions

### ISSUE THREAD

**Issue by beni9n** [Ardulink/Ardulink-2#35]
Hello. I'm not sure if this is the right place to ask this, but here goes.

I want to use Ardulink to publish commands to Mosquitto by pressing a button on the Arduino. I also want subscriptions to Mosquitto to operate an LED on the Arduino. I have Ardulink, Ardulink-MQTT, Mosquitto, etc installed on Ubuntu 16.04 and everything is working. But I'm not sure what the next step is.

I have a more thorough write up of my issue on the [Arduino forum](https://forum.arduino.cc/index.php?topic=526130.0). 

Thank you,
Jeremy

**Comment by pfichtner** [comment]
Not the right place to ask, but let me give you some hints as this could be done very easy: 
either use Ardulink Console or ardulink-mqtt. Enable listening on the digital pin the button is connected to by either clicking the button "Digital sensor panel" in the UI or passing "-d X" where X is digital pin the button is connected to, to ardulink-mqtt

For the LED you just have to publish a message to the broker. The default topic ardulink is listening to is home/devices/ardulink so when sending a message "1" to the topic "home/devices/ardulink/Dx/value/set" where x is the digital pin the LED is connected to, your LED should lighten up
