### ISSUE TITLE
Servo

### ISSUE THREAD

**Issue by Jack0075** [Ardulink/Ardulink-2#36]
Ti ringrazio per la bellissima libreria utilissima,
volevo sapere se era possibile controllare direttamente dei servo, pensavo di inviare un msg ad arduino con i dati dei servo. c'è la possibilità di un controllo diretto?

grazie
Giacomo

**Comment by LucianoZu** [comment]
Ciao Giacomo,

questo non è il posto migliore per fare domande. Puoi chiedere ulteriori informazioni sul nostro sito:
www.ardulink.org

In ogni caso la risposta è sì e no. Sì perché esiste un comando custom che quindi puoi personalizzare, no perché non esiste un comando "nativo" per muovere servo motori. Non esiste perché di base Ardulink invia messaggi per attivare le API native di Arduino, quindi ad esempio imposta HIGH su di un determinato PIN.

Esiste un esempio ahimé non completo per i servomotori. Lo trovi qui:
https://github.com/Ardulink/Ardulink-2/blob/master/deploy-dist/rootfolder/examples/meArm/sketch/Ardulink4MeArm/Ardulink4MeArm.ino

Lo avevo iniziato per controllare un meArm. Puoi provare lo sketch anche con la Ardulink Console utilizzando un SignalButton:
https://github.com/Ardulink/Ardulink-2/blob/master/ardulink-swing/src/main/java/org/ardulink/gui/customcomponents/SignalButton.java

Fammi sapere, chiedendo sul sito, se hai qualche altra domanda.
