### ISSUE TITLE
Migrate mqtt to apache camel

### ISSUE THREAD

**Issue by pfichtner** [Ardulink/Ardulink-2#4]
Instead of directly referring  mqtt third party mqtt libraries we could integrate into apache camel like we did with ardulink-mail.

**Comment by LucianoZu** [comment]
Yes, we should define a module software with the generic Camel Endpoint for Ardulink (taking it from ardulink-mail) and then use it with ardulink-mail and ardulink-mqtt

**Comment by pfichtner** [comment]
I started working on that last week

**Comment by pfichtner** [comment]
Mqtt now using camel but still some work to do because "Ardulink camel" component was not generalized but copied. So some unification work has to be done.

**Comment by pfichtner** [comment]
All done! Now there is a generic Ardulink-Camel component which is used by Mqtt and Mail. A Rest integration would now be easy to implement.

**Comment by pfichtner** [comment]
Supports #5 and can be closes with next release
