### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by donatog** [Ardulink/Ardulink-2#43]
Hi There!
When I try to send via the panel monitor a command to arduino, I get the error java.lang.null.pointer. The connection uses serial-jssc library.
Why this?
Thanks in advance

**Comment by pfichtner** [comment]
Please attach the stacktrace for analyzing the problem

**Comment by donatog** [comment]
[log.txt](https://github.com/Ardulink/Ardulink-2/files/3097801/log.txt)

**Comment by pfichtner** [comment]
Fixed on master, fix will be available on next build/release

**Comment by donatog** [comment]
Ok.
Thanks
