### ISSUE TITLE
LCD control

### ISSUE THREAD

**Issue by donatog** [Ardulink/Ardulink-2#48]
Hi!
Does the ardulink protocol implement an LCD control library too?

**Comment by LucianoZu** [comment]
Ardulink can send custom messages. So you can control whatever you want but if course you have to modify ardulink sketch accordingly.

**Comment by donatog** [comment]
So, for example, I have to include LCD library and codify messages in the ArdulinkProtocol to interpret commands to the LCD, is it right?

**Comment by LucianoZu** [comment]
Yes it's fight. You can see some of our examples too. This is one: https://github.com/Ardulink/Ardulink-2/blob/master/deploy-dist/rootfolder/examples/ButtonQuest/sketch/ButtonQuest/ButtonQuest.ino
