### ISSUE TITLE
Create REST showcase

### ISSUE THREAD

**Issue by pfichtner** [Ardulink/Ardulink-2#5]
To enable rest services we should create an apache camel based showcase.

**Comment by LucianoZu** [comment]
Yes, Camel is a good choice. An ardulink-camel sub module has to be created moving code from ardulink-mail.

Please consider also Spring Boot technology to allow cloud ready showcase.

**Comment by pfichtner** [comment]
> Done with module `ardulink-rest` but not yet published

`ardulink-rest` published
