### ISSUE TITLE
Custom components panel

### ISSUE THREAD

**Issue by donatog** [Ardulink/Ardulink-2#50]
Please,
Could I send a command as "ppin" or "ppsw" through the panel above?
If so, whats the command format?
Thanks

**Comment by LucianoZu** [comment]
Do you mean this component?
https://github.com/Ardulink/Ardulink-2/blob/master/ardulink-swing/src/main/java/org/ardulink/gui/customcomponents/SignalButton.java

If so, no you cannot send an ardulink native ppin or ppsw command but just custom commands. Of course you can define a custom command to do a ppin or a ppsw action.

**Comment by donatog** [comment]
Thanks of your courtesy.
