### ISSUE TITLE
connection notifies

### ISSUE THREAD

**Issue by LucianoZu** [Ardulink/Ardulink-2#7]
connection behavior has to be reviewed. Actually Console connect button doesn't work as expected

**Comment by pfichtner** [comment]
confirmed, will fix it

**Comment by LucianoZu** [comment]
I think could be useful that Link interface has the method isClosed (or isConnected) to help status management on setLink methods of Linkable interface.
Actually new Link interface hasn't connect method as the old one but maybe is not required to have.

**Comment by pfichtner** [comment]
A created Link is an open connection created of the attributes of a config object. If it's broken it's eay to create a new one. Certainly not all link types will be able to handle connection state, e.g. notice if the underlying connection is broken. So I didn't want to mess the general Link interface with things not all Link types are able to fulfill. I'll take a look what could be a possible solution.

**Comment by pfichtner** [comment]
@LucianoZu could you please verify if the issue was fixed? (should work since yesterday)

**Comment by LucianoZu** [comment]
Ok, it works very fine. I've changed just a little enabling/disabling components code
